### PR TITLE
Change the translation in workspace

### PR DESCRIPTION
**Pull request by zak39**
I changed the translation "space" to "workspace" in the RemoveSpace.vue.

@Clementine46 and @dorianne-arawa , it's okay for you ?

image

### CODE REVIEW

**Comment by dorianne-arawa** [comment]
I think it's ok both in french and english. But just to be sure, can you show a screenshot with the english version?
@zak39

**Comment by zak39** [comment]
> I think it's ok both in french and english. But just to be sure, can you show a screenshot with the english version? @zak39

Sure @dorianne-arawa :+1: 

This here the screenshot in the english version : 

image

It's okay for you ?

**Comment by dorianne-arawa** [comment]
Great, it's ok @zak39 thank you

**Pull request merged**
