### PR TITLE
Running Workspace with php8

### PR DESCRIPTION
**Pull request by zak39**
This PR fix the Workspace app to run with PHP8.

Environment :

- NC 23.0.2
- PHP 8.0.16

Here are some examples.

# Create space

php8-create-space

# Add Users and change their roles

# Create a subgroup, add users in this subgroup and delete users in this subgroup

php8-create-subgroups-addusers-deleteusers

# Change the color and quota

php8-change-color-quota

# Rename Space

php8-rename-space

@LivOriona : It's okay for you ?

### CODE REVIEW

**Comment by LivOriona** [comment]
It seems great for me, at first view.
Isn't it possible to have the workspace creation option + view all workspaces option at the top of the side bar ?
@zak39

**Comment by zak39** [comment]
> 

Hi @LivOriona :wave: 

These points are already fixed in another PR :point_right: https://github.com/arawa/workspace/pull/424

**Comment by LivOriona** [comment]
Ok, perfect for me @zak39

**Comment by LivOriona** [comment]
You can validate it @zak39

**Pull request merged**
