### PR TITLE
Add Czech localization - js.variant

### PR DESCRIPTION
**Pull request by p-bo**

### CODE REVIEW

**Comment by zak39** [comment]
Hi @p-bo :)

I am checking if all the texts are translated.

I see the "Role" column is not translated :point_down: 

image

Is this normal, or it's an oversight ?

If not I'm good to go :wink:

**Comment by p-bo** [comment]
Hi @zak39 :-)
it is intentional - the same word belongs there in Czech too

**Comment by p-bo** [comment]
Speaking of translations,
would it be possible to follow instructions on:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#adding-translations
...and gain benefits from work of whole Nextcloud translators community for users of your app please?

For instance:

- much more translators will get involved, because without it, they will newer even know about possibility to translate this app - example of benefits for project known in this manner for community of Nextcloud translators (app with recently added to this workflow, based on same request as this one): https://github.com/H2CK/oidc/commit/937fc37d7797fecc9f4f49e12a154cd8987cf99c (se this and ongoing Nextcloud bot commits - translation of app is getting completed/improved in no time)
- also, as app is evolving, when some string(s) in app is/are changed/added, in case of continuous translation workflow translators are noticed intermediately and strings are translated before new version is released. In contrast with situation, that this change (in source strings) is only silently published in git repo and no one will (get) notice(d) till never version with untranslated strings get released (proactive vs retroactive)).
- when one (of translators) will during using this app notice possibility to translate something in better manner, it is much efficient (especially for minor changes) to do this in translation tool than edit file directly in git. For example in case of one letter changes (misspelled words, etc.) has change directly in git such overhead (many steps to change just one letter), that these type of tweaks are rare due this (loss of quality for users)

To conclude: with continuous translation workflow, result is, that users of your app are getting more complete and more polished localization, so their user experience is much more pleasant.

**Comment by zak39** [comment]
> Hi @zak39 :-) it is intentional - the same word belongs there in Czech too

Good if it's not an error :)

> Speaking of translations, would it be possible to follow instructions on: https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#adding-translations ...and gain benefits from work of whole Nextcloud translators community for users of your app please?
> 
> For instance:
> 
>     * much more translators will get involved, because without it, they will newer even know about possibility to translate this app - example of benefits for project known in this manner for community of Nextcloud translators (app with recently added to this workflow, based on same request as this one): [H2CK/oidc@937fc37](https://github.com/H2CK/oidc/commit/937fc37d7797fecc9f4f49e12a154cd8987cf99c) (se this and ongoing Nextcloud bot commits - translation of app is getting completed/improved in no time)
> 
>     * also, as app is evolving, when some string(s) in app is/are changed/added, in case of continuous translation workflow translators are noticed intermediately and strings are translated before new version is released. In contrast with situation, that this change (in source strings) is only silently published in git repo and no one will (get) notice(d) till never version with untranslated strings get released (proactive vs retroactive)).
> 
>     * when one (of translators) will during using this app notice possibility to translate something in better manner, it is much efficient (especially for minor changes) to do this in translation tool than edit file directly in git. For example in case of one letter changes (misspelled words, etc.) has change directly in git such overhead (many steps to change just one letter), that these type of tweaks are rare due this (loss of quality for users)
> 
> 
> To conclude: with continuous translation workflow, result is, that users of your app are getting more complete and more polished localization, so their user experience is much more pleasant.

Yes, I can do this ! I will create an issue on this subject and I will add this feature :wink:

**Pull request merged**
